jobs:
  build:
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Compile java file
        uses: actions/setup-java@v4
        with:
          java-version: 25
        run: |
          javac Hello.java


